<?php
session_start();
require_once 'config/db_connect.php';
require_once 'functions.php';

$token = $_GET['token'] ?? '';
$stmt = $pdo->prepare("SELECT user_id FROM users WHERE verification_token = ? AND email_verified = FALSE");
$stmt->execute([$token]);
$user = $stmt->fetch(PDO::FETCH_ASSOC);

if ($user) {
    $stmt = $pdo->prepare("UPDATE users SET email_verified = TRUE, verification_token = NULL WHERE user_id = ?");
    $stmt->execute([$user['user_id']]);
    echo "Email verified successfully. <a href='login.php'>Login</a>";
} else {
    echo "Invalid or expired verification token.";
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>Verify Email</title>
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
    <div class="centered-content">
        <!-- Content is dynamically generated by PHP -->
    </div>
</body>
</html>